export const ZOOM_TIMEOUT = 20
export const SCROLL_END_TIMEOUT = 20

export const REFRESH_CLAIM_INTERVAL = 30000
export const REFRESH_PASSES_INTERVAL = 30000
export const REFRESH_WEAPONS_COUNT_INTERVAL = 5000

export const REFRESH_STAKING_STATUS_TIMEOUT = 2000

export const SPIN_ROULETTE_TIMEOUT = 1500